### ISSUE TITLE
How to add Transactional trait

### ISSUE THREAD

**Issue by tinkhauser** [ryankurte/embedded-hal-compat#2]
I'm attempting to get the `rust-radio-sx128x` crate working with the `nrf-hal`. That hal hasn't yet implemented the `v1.0.0-alpha.N` `embedded-hal` traits.

So far `compat()` has solved all the trait errors except for `blocking::spi::transactional`. I'm unsure of how to add that trait to this crate.

Is it possible to add the `transactional` trait to this repo? Or do I need to fork `nrf-hal` and implement it there like you suggest here? https://github.com/rust-iot/rust-radio-sx127x/issues/18#issuecomment-782782909

Cheers!

**Comment by ryankurte** [comment]
Ahh, I didn't put it in because `embedded_hal::blocking::spi::Transactional` doesn't _exist_ until `v1.0.0-alpha.X`...

In the past I had a [polyfill](https://github.com/ryankurte/rust-driver-pal/blob/v0.6.2/src/wrapper.rs#L175) for this, technically it opens a whole `CS` related can of worms but, might as well add have it here anyway (perhaps with a warning and link to https://github.com/rust-embedded/embedded-hal/issues/180)?

**Comment by ryankurte** [comment]
@tinkhauser i threw a `Transactional` trait in there so you should be good to go with `0.1.3`, let me know how it goes?
